import type { User, Server, Message, Channel } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    username: "starlily",
    displayName: "Lily ✨",
    avatar: undefined,
    avatarType: "image",
    avatarShape: "circle",
    avatarEffect: "sparkle",
    banner: undefined,
    status: "online",
    customStatus: "listening to music 🎵",
    pronouns: "she/her",
    bio: "artist & dreamer. i make things pretty. ☁️\n\n*open for commissions!*",
    identityTags: [
      { id: "t1", label: "artist", color: "#c084fc" },
      { id: "t2", label: "she/her", color: "#fb7185" },
      { id: "t3", label: "gamer", color: "#38bdf8" },
    ],
    badges: [
      { id: "b1", label: "Early Adopter", icon: "⭐", color: "#fbbf24", description: "Joined Lyra in the first month" },
      { id: "b2", label: "Artist", icon: "🎨", color: "#c084fc", description: "Verified artist" },
    ],
    customLinks: [
      { label: "My Portfolio", url: "https://example.com" },
      { label: "Ko-fi", url: "https://ko-fi.com" },
    ],
    displayColor: "#c084fc",
    displayFont: "Inter",
    role: "user",
    joinedAt: "2024-01-15T12:00:00Z",
    spotifyConnected: true,
    nowPlaying: {
      id: "track-1",
      name: "Espresso",
      artist: "Sabrina Carpenter",
      album: "Short n' Sweet",
      albumArt: "/api/placeholder/60/60",
      duration: 175000,
      progress: 62000,
      isPlaying: true,
    },
    privacy: {
      bio: "everyone",
      customLinks: "everyone",
      status: "everyone",
      widgets: "everyone",
      mutualInfo: "everyone",
      joinDate: "everyone",
    },
    theme: "lyra-default",
  },
  {
    id: "user-2",
    username: "nox_void",
    displayName: "Nox",
    avatarShape: "squircle",
    avatarEffect: "neon",
    status: "dnd",
    customStatus: "coding in the dark",
    pronouns: "they/them",
    bio: "backend dev by day. dungeon master by night.",
    identityTags: [
      { id: "t4", label: "developer", color: "#4ade80" },
      { id: "t5", label: "they/them", color: "#a855f7" },
    ],
    badges: [
      { id: "b3", label: "Developer", icon: "⚙️", color: "#4ade80", description: "Lyra developer" },
    ],
    customLinks: [],
    displayColor: "#4ade80",
    displayFont: "Inter",
    role: "admin",
    joinedAt: "2024-01-10T08:00:00Z",
    spotifyConnected: false,
    privacy: {
      bio: "everyone",
      customLinks: "friends",
      status: "everyone",
      widgets: "everyone",
      mutualInfo: "friends",
      joinDate: "everyone",
    },
    theme: "obsidian",
  },
  {
    id: "user-3",
    username: "aurora_sky",
    displayName: "Aurora 🌌",
    avatarShape: "circle",
    status: "idle",
    pronouns: "she/they",
    bio: "stargazer. photographer. coffee addict.",
    identityTags: [
      { id: "t6", label: "photographer", color: "#38bdf8" },
    ],
    badges: [],
    customLinks: [],
    displayColor: "#38bdf8",
    displayFont: "Inter",
    role: "user",
    joinedAt: "2024-02-01T15:30:00Z",
    spotifyConnected: true,
    privacy: {
      bio: "everyone",
      customLinks: "everyone",
      status: "everyone",
      widgets: "everyone",
      mutualInfo: "everyone",
      joinDate: "everyone",
    },
    theme: "ocean",
  },
];

export const CURRENT_USER = MOCK_USERS[0];

export const MOCK_SERVERS: Server[] = [
  {
    id: "server-1",
    name: "Lyra HQ",
    ownerId: "user-2",
    memberCount: 1247,
    boostCount: 12,
    categories: [
      {
        id: "cat-1",
        name: "WELCOME",
        serverId: "server-1",
        collapsed: false,
        channels: [
          { id: "ch-1", name: "rules", type: "announcements", categoryId: "cat-1", serverId: "server-1", topic: "Read these before chatting!", unread: false, mentionCount: 0 },
          { id: "ch-2", name: "announcements", type: "announcements", categoryId: "cat-1", serverId: "server-1", topic: "Official Lyra updates", unread: true, mentionCount: 0 },
        ],
      },
      {
        id: "cat-2",
        name: "GENERAL",
        serverId: "server-1",
        collapsed: false,
        channels: [
          { id: "ch-3", name: "general", type: "text", categoryId: "cat-2", serverId: "server-1", topic: "Chat about anything!", unread: true, mentionCount: 2 },
          { id: "ch-4", name: "off-topic", type: "text", categoryId: "cat-2", serverId: "server-1", unread: false, mentionCount: 0 },
          { id: "ch-5", name: "showcase", type: "text", categoryId: "cat-2", serverId: "server-1", topic: "Share your work!", unread: true, mentionCount: 0 },
          { id: "ch-6", name: "music-vibes", type: "music", categoryId: "cat-2", serverId: "server-1", topic: "Share what you're listening to", unread: false, mentionCount: 0 },
          { id: "ch-7", name: "polls", type: "polls", categoryId: "cat-2", serverId: "server-1", unread: false, mentionCount: 0 },
        ],
      },
      {
        id: "cat-3",
        name: "VOICE",
        serverId: "server-1",
        collapsed: false,
        channels: [
          { id: "ch-8", name: "Lounge", type: "voice", categoryId: "cat-3", serverId: "server-1", unread: false, mentionCount: 0 },
          { id: "ch-9", name: "Gaming", type: "voice", categoryId: "cat-3", serverId: "server-1", unread: false, mentionCount: 0 },
          { id: "ch-10", name: "Study Hall", type: "voice", categoryId: "cat-3", serverId: "server-1", unread: false, mentionCount: 0 },
          { id: "ch-11", name: "Watch Party", type: "video", categoryId: "cat-3", serverId: "server-1", unread: false, mentionCount: 0 },
        ],
      },
    ],
  },
  {
    id: "server-2",
    name: "Art & Design",
    ownerId: "user-1",
    memberCount: 389,
    boostCount: 3,
    categories: [
      {
        id: "cat-4",
        name: "GENERAL",
        serverId: "server-2",
        collapsed: false,
        channels: [
          { id: "ch-12", name: "general", type: "text", categoryId: "cat-4", serverId: "server-2", unread: false, mentionCount: 0 },
          { id: "ch-13", name: "inspiration", type: "text", categoryId: "cat-4", serverId: "server-2", unread: true, mentionCount: 1 },
          { id: "ch-14", name: "wip", type: "text", categoryId: "cat-4", serverId: "server-2", topic: "Share works in progress", unread: false, mentionCount: 0 },
        ],
      },
    ],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg-1",
    channelId: "ch-3",
    authorId: "user-2",
    author: MOCK_USERS[1],
    content: "hey everyone! welcome to the new **#general** channel 🎉",
    createdAt: "2024-04-19T10:00:00Z",
    reactions: [
      { emoji: "🎉", count: 12, userIds: ["user-1", "user-3"], animated: false },
      { emoji: "❤️", count: 8, userIds: ["user-1"], animated: false },
    ],
    attachments: [],
    pinned: true,
    type: "default",
  },
  {
    id: "msg-2",
    channelId: "ch-3",
    authorId: "user-3",
    author: MOCK_USERS[2],
    content: "this is so cool!! love the new look 🌌✨",
    createdAt: "2024-04-19T10:02:00Z",
    reactions: [
      { emoji: "✨", count: 5, userIds: ["user-1"], animated: false },
    ],
    attachments: [],
    pinned: false,
    type: "default",
  },
  {
    id: "msg-3",
    channelId: "ch-3",
    authorId: "user-1",
    author: MOCK_USERS[0],
    content: "omg the profile customization is everything 😭💜 i spent way too long on my avatar effects lol",
    createdAt: "2024-04-19T10:05:00Z",
    reactions: [],
    attachments: [],
    pinned: false,
    type: "default",
  },
  {
    id: "msg-4",
    channelId: "ch-3",
    authorId: "user-2",
    author: MOCK_USERS[1],
    content: "haha you can change them any time too! all effects are free forever, no Nitro nonsense here",
    createdAt: "2024-04-19T10:06:00Z",
    reactions: [
      { emoji: "🙌", count: 20, userIds: ["user-1", "user-3"], animated: false },
    ],
    attachments: [],
    pinned: false,
    type: "default",
  },
  {
    id: "msg-5",
    channelId: "ch-3",
    authorId: "user-1",
    author: MOCK_USERS[0],
    content: "also the Spotify integration is insane, my now playing shows up on my profile card 🎵",
    createdAt: "2024-04-19T10:10:00Z",
    reactions: [
      { emoji: "🎵", count: 7, userIds: ["user-2", "user-3"], animated: false },
    ],
    attachments: [],
    replyTo: undefined,
    pinned: false,
    type: "default",
  },
  {
    id: "msg-6",
    channelId: "ch-3",
    authorId: "user-3",
    author: MOCK_USERS[2],
    content: "wait you can have animated banners too?? i need to test this",
    createdAt: "2024-04-19T10:12:00Z",
    reactions: [],
    attachments: [],
    pinned: false,
    type: "default",
  },
  {
    id: "msg-7",
    channelId: "ch-3",
    authorId: "user-2",
    author: MOCK_USERS[1],
    content: "yep! go to Settings → Profile → Banner. you can upload a GIF or pick from animated presets",
    createdAt: "2024-04-19T10:13:00Z",
    reactions: [
      { emoji: "👀", count: 4, userIds: ["user-3"], animated: false },
    ],
    attachments: [],
    pinned: false,
    type: "default",
  },
];
