import type { Theme } from "./types";

export const THEMES: Theme[] = [
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep dark blue, elegant and calm",
    preview: {
      primaryBg: "#0d1117",
      secondaryBg: "#161b22",
      sidebarBg: "#010409",
      accent: "#58a6ff",
      textPrimary: "#e6edf3",
    },
    tokens: {
      primaryBg: "#0d1117",
      secondaryBg: "#161b22",
      tertiaryBg: "#21262d",
      sidebarBg: "#010409",
      channelSidebarBg: "#0d1117",
      chatBg: "#0d1117",
      messageBg: "#161b22",
      accent: "#58a6ff",
      accentHover: "#79b8ff",
      textPrimary: "#e6edf3",
      textSecondary: "#8b949e",
      textMuted: "#6e7681",
      border: "#30363d",
      buttonPrimary: "#238636",
      buttonPrimaryText: "#ffffff",
      inputBg: "#161b22",
      inputBorder: "#30363d",
      statusOnline: "#3fb950",
      statusIdle: "#d29922",
      statusDnd: "#f85149",
      statusOffline: "#6e7681",
      scrollbar: "#30363d",
      scrollbarHover: "#58a6ff",
    },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "Pure dark, minimal and clean",
    preview: {
      primaryBg: "#1a1a1a",
      secondaryBg: "#242424",
      sidebarBg: "#111111",
      accent: "#7c3aed",
      textPrimary: "#f5f5f5",
    },
    tokens: {
      primaryBg: "#1a1a1a",
      secondaryBg: "#242424",
      tertiaryBg: "#2e2e2e",
      sidebarBg: "#111111",
      channelSidebarBg: "#1a1a1a",
      chatBg: "#1a1a1a",
      messageBg: "#242424",
      accent: "#7c3aed",
      accentHover: "#8b5cf6",
      textPrimary: "#f5f5f5",
      textSecondary: "#a3a3a3",
      textMuted: "#737373",
      border: "#3a3a3a",
      buttonPrimary: "#7c3aed",
      buttonPrimaryText: "#ffffff",
      inputBg: "#2e2e2e",
      inputBorder: "#3a3a3a",
      statusOnline: "#22c55e",
      statusIdle: "#eab308",
      statusDnd: "#ef4444",
      statusOffline: "#6b7280",
      scrollbar: "#3a3a3a",
      scrollbarHover: "#7c3aed",
    },
  },
  {
    id: "rose-dawn",
    name: "Rose Dawn",
    description: "Warm pink and rose tones",
    preview: {
      primaryBg: "#1f0f12",
      secondaryBg: "#2d1418",
      sidebarBg: "#160a0d",
      accent: "#fb7185",
      textPrimary: "#fce7f3",
    },
    tokens: {
      primaryBg: "#1f0f12",
      secondaryBg: "#2d1418",
      tertiaryBg: "#3d1a20",
      sidebarBg: "#160a0d",
      channelSidebarBg: "#1f0f12",
      chatBg: "#1f0f12",
      messageBg: "#2d1418",
      accent: "#fb7185",
      accentHover: "#fda4af",
      textPrimary: "#fce7f3",
      textSecondary: "#f9a8d4",
      textMuted: "#f472b6",
      border: "#4d2030",
      buttonPrimary: "#be185d",
      buttonPrimaryText: "#ffffff",
      inputBg: "#2d1418",
      inputBorder: "#4d2030",
      statusOnline: "#4ade80",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#4d2030",
      scrollbarHover: "#fb7185",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Deep greens and earth tones",
    preview: {
      primaryBg: "#0a1a0f",
      secondaryBg: "#112016",
      sidebarBg: "#061009",
      accent: "#4ade80",
      textPrimary: "#dcfce7",
    },
    tokens: {
      primaryBg: "#0a1a0f",
      secondaryBg: "#112016",
      tertiaryBg: "#1a3025",
      sidebarBg: "#061009",
      channelSidebarBg: "#0a1a0f",
      chatBg: "#0a1a0f",
      messageBg: "#112016",
      accent: "#4ade80",
      accentHover: "#86efac",
      textPrimary: "#dcfce7",
      textSecondary: "#86efac",
      textMuted: "#4ade80",
      border: "#1e4030",
      buttonPrimary: "#16a34a",
      buttonPrimaryText: "#ffffff",
      inputBg: "#112016",
      inputBorder: "#1e4030",
      statusOnline: "#4ade80",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#1e4030",
      scrollbarHover: "#4ade80",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep sea blues and teals",
    preview: {
      primaryBg: "#0a1628",
      secondaryBg: "#0f2040",
      sidebarBg: "#061020",
      accent: "#38bdf8",
      textPrimary: "#e0f2fe",
    },
    tokens: {
      primaryBg: "#0a1628",
      secondaryBg: "#0f2040",
      tertiaryBg: "#162a55",
      sidebarBg: "#061020",
      channelSidebarBg: "#0a1628",
      chatBg: "#0a1628",
      messageBg: "#0f2040",
      accent: "#38bdf8",
      accentHover: "#7dd3fc",
      textPrimary: "#e0f2fe",
      textSecondary: "#7dd3fc",
      textMuted: "#38bdf8",
      border: "#1e3a6e",
      buttonPrimary: "#0284c7",
      buttonPrimaryText: "#ffffff",
      inputBg: "#0f2040",
      inputBorder: "#1e3a6e",
      statusOnline: "#34d399",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#1e3a6e",
      scrollbarHover: "#38bdf8",
    },
  },
  {
    id: "galaxy",
    name: "Galaxy",
    description: "Cosmic purples and starlight",
    preview: {
      primaryBg: "#0d0820",
      secondaryBg: "#160f30",
      sidebarBg: "#080514",
      accent: "#a855f7",
      textPrimary: "#f3e8ff",
    },
    tokens: {
      primaryBg: "#0d0820",
      secondaryBg: "#160f30",
      tertiaryBg: "#1e1440",
      sidebarBg: "#080514",
      channelSidebarBg: "#0d0820",
      chatBg: "#0d0820",
      messageBg: "#160f30",
      accent: "#a855f7",
      accentHover: "#c084fc",
      textPrimary: "#f3e8ff",
      textSecondary: "#d8b4fe",
      textMuted: "#a855f7",
      border: "#2d1b5e",
      buttonPrimary: "#7c3aed",
      buttonPrimaryText: "#ffffff",
      inputBg: "#160f30",
      inputBorder: "#2d1b5e",
      statusOnline: "#34d399",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#2d1b5e",
      scrollbarHover: "#a855f7",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm oranges and amber",
    preview: {
      primaryBg: "#1a0f05",
      secondaryBg: "#271609",
      sidebarBg: "#110a03",
      accent: "#fb923c",
      textPrimary: "#fff7ed",
    },
    tokens: {
      primaryBg: "#1a0f05",
      secondaryBg: "#271609",
      tertiaryBg: "#3d2010",
      sidebarBg: "#110a03",
      channelSidebarBg: "#1a0f05",
      chatBg: "#1a0f05",
      messageBg: "#271609",
      accent: "#fb923c",
      accentHover: "#fdba74",
      textPrimary: "#fff7ed",
      textSecondary: "#fed7aa",
      textMuted: "#fb923c",
      border: "#4d2a10",
      buttonPrimary: "#c2410c",
      buttonPrimaryText: "#ffffff",
      inputBg: "#271609",
      inputBorder: "#4d2a10",
      statusOnline: "#4ade80",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#4d2a10",
      scrollbarHover: "#fb923c",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    description: "Cool icy whites and blues",
    preview: {
      primaryBg: "#f0f4f8",
      secondaryBg: "#e2e8f0",
      sidebarBg: "#dde3ea",
      accent: "#3b82f6",
      textPrimary: "#1e293b",
    },
    tokens: {
      primaryBg: "#f0f4f8",
      secondaryBg: "#e2e8f0",
      tertiaryBg: "#cbd5e1",
      sidebarBg: "#dde3ea",
      channelSidebarBg: "#e8eef4",
      chatBg: "#f8fafc",
      messageBg: "#ffffff",
      accent: "#3b82f6",
      accentHover: "#60a5fa",
      textPrimary: "#1e293b",
      textSecondary: "#475569",
      textMuted: "#94a3b8",
      border: "#cbd5e1",
      buttonPrimary: "#3b82f6",
      buttonPrimaryText: "#ffffff",
      inputBg: "#ffffff",
      inputBorder: "#cbd5e1",
      statusOnline: "#22c55e",
      statusIdle: "#eab308",
      statusDnd: "#ef4444",
      statusOffline: "#94a3b8",
      scrollbar: "#cbd5e1",
      scrollbarHover: "#3b82f6",
    },
  },
  {
    id: "cherry",
    name: "Cherry Blossom",
    description: "Soft pinks and light sakura",
    preview: {
      primaryBg: "#fff0f3",
      secondaryBg: "#ffe4e9",
      sidebarBg: "#ffd6de",
      accent: "#e11d48",
      textPrimary: "#1a0a10",
    },
    tokens: {
      primaryBg: "#fff0f3",
      secondaryBg: "#ffe4e9",
      tertiaryBg: "#fecdd3",
      sidebarBg: "#ffd6de",
      channelSidebarBg: "#fff0f3",
      chatBg: "#fffbfc",
      messageBg: "#ffffff",
      accent: "#e11d48",
      accentHover: "#fb7185",
      textPrimary: "#1a0a10",
      textSecondary: "#6d2a3a",
      textMuted: "#be185d",
      border: "#fecdd3",
      buttonPrimary: "#be185d",
      buttonPrimaryText: "#ffffff",
      inputBg: "#ffffff",
      inputBorder: "#fecdd3",
      statusOnline: "#16a34a",
      statusIdle: "#ca8a04",
      statusDnd: "#dc2626",
      statusOffline: "#9ca3af",
      scrollbar: "#fecdd3",
      scrollbarHover: "#e11d48",
    },
  },
  {
    id: "neon",
    name: "Neon City",
    description: "Cyberpunk neons on deep black",
    preview: {
      primaryBg: "#050510",
      secondaryBg: "#0a0a20",
      sidebarBg: "#030308",
      accent: "#00ff88",
      textPrimary: "#e0fff0",
    },
    tokens: {
      primaryBg: "#050510",
      secondaryBg: "#0a0a20",
      tertiaryBg: "#10102e",
      sidebarBg: "#030308",
      channelSidebarBg: "#050510",
      chatBg: "#050510",
      messageBg: "#0a0a20",
      accent: "#00ff88",
      accentHover: "#33ffaa",
      textPrimary: "#e0fff0",
      textSecondary: "#00ff88",
      textMuted: "#00cc6a",
      border: "#0a2a1a",
      buttonPrimary: "#00cc6a",
      buttonPrimaryText: "#000000",
      inputBg: "#0a0a20",
      inputBorder: "#00ff8840",
      statusOnline: "#00ff88",
      statusIdle: "#ffaa00",
      statusDnd: "#ff0066",
      statusOffline: "#336655",
      scrollbar: "#0a2a1a",
      scrollbarHover: "#00ff88",
    },
  },
  {
    id: "mocha",
    name: "Mocha",
    description: "Rich browns and coffee tones",
    preview: {
      primaryBg: "#1c1410",
      secondaryBg: "#261e18",
      sidebarBg: "#120d09",
      accent: "#c7934a",
      textPrimary: "#f5ede3",
    },
    tokens: {
      primaryBg: "#1c1410",
      secondaryBg: "#261e18",
      tertiaryBg: "#342820",
      sidebarBg: "#120d09",
      channelSidebarBg: "#1c1410",
      chatBg: "#1c1410",
      messageBg: "#261e18",
      accent: "#c7934a",
      accentHover: "#d4a874",
      textPrimary: "#f5ede3",
      textSecondary: "#c4a882",
      textMuted: "#8a7060",
      border: "#3d2e22",
      buttonPrimary: "#7c4a1e",
      buttonPrimaryText: "#f5ede3",
      inputBg: "#261e18",
      inputBorder: "#3d2e22",
      statusOnline: "#56b870",
      statusIdle: "#d4a020",
      statusDnd: "#c0504a",
      statusOffline: "#6b5a4e",
      scrollbar: "#3d2e22",
      scrollbarHover: "#c7934a",
    },
  },
  {
    id: "lyra-default",
    name: "Lyra Default",
    description: "The signature Lyra experience",
    preview: {
      primaryBg: "#1a1230",
      secondaryBg: "#231840",
      sidebarBg: "#130d25",
      accent: "#c084fc",
      textPrimary: "#f3e8ff",
    },
    tokens: {
      primaryBg: "#1a1230",
      secondaryBg: "#231840",
      tertiaryBg: "#2d2050",
      sidebarBg: "#130d25",
      channelSidebarBg: "#1a1230",
      chatBg: "#1a1230",
      messageBg: "#231840",
      accent: "#c084fc",
      accentHover: "#d8b4fe",
      textPrimary: "#f3e8ff",
      textSecondary: "#d8b4fe",
      textMuted: "#a855f7",
      border: "#3b2a6e",
      buttonPrimary: "#7c3aed",
      buttonPrimaryText: "#ffffff",
      inputBg: "#231840",
      inputBorder: "#3b2a6e",
      statusOnline: "#34d399",
      statusIdle: "#fbbf24",
      statusDnd: "#f87171",
      statusOffline: "#6b7280",
      scrollbar: "#3b2a6e",
      scrollbarHover: "#c084fc",
    },
  },
];

export const DEFAULT_THEME_ID = "lyra-default";

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[THEMES.length - 1];
}

export function applyTheme(tokens: Theme["tokens"]): void {
  const root = document.documentElement;
  root.style.setProperty("--lyra-primary-bg", tokens.primaryBg);
  root.style.setProperty("--lyra-secondary-bg", tokens.secondaryBg);
  root.style.setProperty("--lyra-tertiary-bg", tokens.tertiaryBg);
  root.style.setProperty("--lyra-sidebar-bg", tokens.sidebarBg);
  root.style.setProperty("--lyra-channel-sidebar-bg", tokens.channelSidebarBg);
  root.style.setProperty("--lyra-chat-bg", tokens.chatBg);
  root.style.setProperty("--lyra-message-bg", tokens.messageBg);
  root.style.setProperty("--lyra-accent", tokens.accent);
  root.style.setProperty("--lyra-accent-hover", tokens.accentHover);
  root.style.setProperty("--lyra-text-primary", tokens.textPrimary);
  root.style.setProperty("--lyra-text-secondary", tokens.textSecondary);
  root.style.setProperty("--lyra-text-muted", tokens.textMuted);
  root.style.setProperty("--lyra-border", tokens.border);
  root.style.setProperty("--lyra-button-primary", tokens.buttonPrimary);
  root.style.setProperty("--lyra-button-primary-text", tokens.buttonPrimaryText);
  root.style.setProperty("--lyra-input-bg", tokens.inputBg);
  root.style.setProperty("--lyra-input-border", tokens.inputBorder);
  root.style.setProperty("--lyra-status-online", tokens.statusOnline);
  root.style.setProperty("--lyra-status-idle", tokens.statusIdle);
  root.style.setProperty("--lyra-status-dnd", tokens.statusDnd);
  root.style.setProperty("--lyra-status-offline", tokens.statusOffline);
  root.style.setProperty("--lyra-scrollbar", tokens.scrollbar);
  root.style.setProperty("--lyra-scrollbar-hover", tokens.scrollbarHover);
}
